# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/MAS_LRI/PYNQ_const.xdc

# Block Designs: bd/b_d/b_d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_d || ORIG_REF_NAME==b_d} -quiet] -quiet

# IP: bd/b_d/ip/b_d_processing_system7_0_0/b_d_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_d_processing_system7_0_0 || ORIG_REF_NAME==b_d_processing_system7_0_0} -quiet] -quiet

# IP: bd/b_d/ip/b_d_axi_gpio_0_0/b_d_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_d_axi_gpio_0_0 || ORIG_REF_NAME==b_d_axi_gpio_0_0} -quiet] -quiet

# IP: bd/b_d/ip/b_d_xbar_0/b_d_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_d_xbar_0 || ORIG_REF_NAME==b_d_xbar_0} -quiet] -quiet

# IP: bd/b_d/ip/b_d_ps7_0_axi_periph_0/b_d_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_d_ps7_0_axi_periph_0 || ORIG_REF_NAME==b_d_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/b_d/ip/b_d_rst_ps7_0_50M_0/b_d_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_d_rst_ps7_0_50M_0 || ORIG_REF_NAME==b_d_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/b_d/ip/b_d_axi_gpio_1_0/b_d_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_d_axi_gpio_1_0 || ORIG_REF_NAME==b_d_axi_gpio_1_0} -quiet] -quiet

# IP: bd/b_d/ip/b_d_auto_pc_0/b_d_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b_d_auto_pc_0 || ORIG_REF_NAME==b_d_auto_pc_0} -quiet] -quiet

# XDC: bd/b_d/b_d_ooc.xdc
